input_features:
- name: sepal_length
  type: number
- name: sepal_width
  type: number
- name: petal_length
  type: number
- name: petal_width
  type: number
output_features:
- name: species
  type: category
trainer:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  optimizer:
    type: adam
