input_features:
- name: Pclass
  type: category
- name: Sex
  type: category
- name: Age
  type: number
- name: SibSp
  type: number
- name: Parch
  type: number
- name: Fare
  type: number
output_features:
- name: Survived
  type: binary
trainer:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  optimizer:
    type: adam
